### PR TITLE
Allow different director un/password

### PR DESCRIPTION
**Pull request by mikegehard**
This will allow people to add a new bosh director user for AWS to secure the director.

### CODE REVIEW

**Comment by cppforlife** [comment]
@mikegehard there is already BOSH_USER and BOSH_PASSWORD env vars that should be respected by the cli.

**Comment by mikegehard** [comment]
Thanks for the heads up @cppforlife. I'll try using those to override the command line flags in this script although that seems like it would cause more confusion than allowing this script to take arguments.

Would it be better if I defaulted to admin/admin if there were no arguments to preserve the original behavior?

**Comment by mikegehard** [comment]
OK so I tried the above environment variables and they don't seem to override the command line flags used in provision_cf.

I also realized that there are issues defaulting to admin if no options are passed because it will be hard to figure out if the args are un/password or simply additional bosh manifests.

I'll keep poking around to see if there is another option.

**Comment by mikegehard** [comment]
Using env variables to override director un/password instead of arguments. These default to admin/admin if not present.

**Pull request closed without merging**
