### PR TITLE
Add downloaded bosh lite stemcell to gitignore

### PR DESCRIPTION
**Pull request by dlresende**
The process of installing a bosh-lite + cf requires a bosh-lite stemcell to be downloaded. At the end of the process, my local git repository reported some changes:

```bash
± dlr |master ?:1 ✗| → git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        latest-bosh-lite-stemcell-warden.tgz

nothing added to commit but untracked files present (use "git add" to track)
```

This PR adds the downloaded *latest-bosh-lite-stemcell-warden.tgz* to gitignore.

### CODE REVIEW

**Comment by dlresende** [comment]
Hey,

I did publicize my membership of pivotal-cf org.

As per my understanding, that should be enough.

**Comment by dpb587-pivotal** [comment]
Thanks for the PR - can you clarify how you got a file named `latest-bosh*-stemcell-warden.*`? Nowadays, bosh.io should be giving names in a very predictable format of `bosh-stemcell-*-warden-boshlite-ubuntu-trusty-go_agent.tgz`, so I don't think the `.gitignore` should need to change. Hoping you can point us to a doc that we can update instead.

**Comment by dlresende** [comment]
Actually I'm using the `bin/provision_cf` script. That script is [downloading the lite stemcell](https://github.com/cloudfoundry/bosh-lite/blob/master/bin/provision_cf#L53) locally [with a name](https://github.com/cloudfoundry/bosh-lite/blob/master/bin/provision_cf#L6) which currently is not compatible with with [the name in the gitignore](https://github.com/cloudfoundry/bosh-lite/blob/master/.gitignore#L9).

Updating the gitignore seems to be the change with less impact to sort it out.

**Comment by dpb587-pivotal** [comment]
Fair enough - thanks for the links.

For what it's worth, we're trying to encourage people to start using [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment), and, specifically, the [bosh-lite](https://github.com/cloudfoundry/bosh-deployment/blob/master/docs/bosh-lite-on-vbox.md) ops file there. If you get a chance, you might want to try that out.

**Pull request merged**
